Prioritize json settings and optimize UI
usb2snes/LiveSplit.USB2SNESSplitter pull request #8
Opened 2021-02-13 06:27 UTC by idlechild

I believe the edit splits UI is faster than before, and the first time you visit the layout settings is fast.  For whatever reason when you visit layout settings a second time, the tab is still very slow to load when you have a lot of splits.  Hopefully someone can improve that in the future.

I adjusted logic to prioritize the json over previously stored settings, just to make sure if your split name matches a name in the json then that is always selected.  I also fixed a mistake involving subsplits.  Previously I added support for subsplits, but I wasn't saving them properly.  This issue only affected subsplits.

2021-09-14 18:09 UTC, idlechild commented
This PR now includes the timer stutter fix and improved autostart support.

Now that autostart supports more and next, I changed autostart to start on the missile disappearing.  I was not able to get it to false start anymore; it may still be possible but you'd have to be trying.  Previously when I tried starting on the missile disappaearing, simply starting livesplit before the console could trigger a false start when the Nintendo logo appeared.  Now that should not occur.

2021-09-18 17:17 UTC, Bonus36 requested changes
Looks good overall. Just a couple of minor comments to address. Thanks!

2021-09-18 17:17 UTC, Bonus36 commented on Component.cs
> +                    int ms = (int)data[0][0] + ((int)data[0][1] << 8);
Looks like this lost the conversion from frames to ms. It should still multiply by 1000 and divide by 60, right?

2021-09-18 17:17 UTC, Bonus36 commented on Component.cs
> +            addressSizePairs.Add(new Tuple<uint, uint>(split.addressInt, 2));// (split.type == "smboss") ? 16 : 2));
I'm guessing this is comment is just a stray bit of testing code that should be removed?

2021-09-19 17:26 UTC, idlechild commented on Component.cs
> +                    int ms = (int)data[0][0] + ((int)data[0][1] << 8);
Yep I missed that, good catch.  Fixed now.

2021-09-19 17:28 UTC, idlechild commented on Component.cs
> +            addressSizePairs.Add(new Tuple<uint, uint>(split.addressInt, 2));// (split.type == "smboss") ? 16 : 2));
Yep.  I had considered bringing in the randomizer boss splits work, but if I did it then I would make it more generic (I agree with skarsnik's comments on that).  However I soon realized it was more work than I wanted to take on so I dropped it.  This comment got left behind.  It's now removed.

2021-09-19 19:22 UTC, Bonus36 approved these changes

2021-09-19 19:23 UTC, merged